### ISSUE TITLE
'Ruby LSP' formatter hanging on save

### ISSUE THREAD

**Issue by davidcelis** [Shopify/ruby-lsp#1663]
### Operating System

macOS Sonoma 14.3.1 (23D60)

### Ruby version

3.0.6p216

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

asdf

### Description

Since updating VSCode to the newest version this morning, the Ruby LSP extension reliably enters a corrupted state where it's not able to format on save. At first, the LSP extension would be usable for a couple minutes before this happens; however, I just ran a system update just in case and went from macOS 14.3.0 to 14.3.1. Since restarting, the LSP extension is immediately unusable, with the format dialogue showing up after a few seconds and not going away. There isn't anything helpful in the output, from what I can tell:

```
2024-02-20 13:02:16.655 [info] (laddertruck) Checking if asdf is available on the path with command: /opt/homebrew/bin/fish -i -c 'asdf --version'
2024-02-20 13:02:16.731 [info] (laddertruck) Discovered version manager asdf
2024-02-20 13:02:16.736 [info] (laddertruck) Trying to activate Ruby environment with command: /opt/homebrew/bin/fish -i -c 'asdf exec ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))"' inside directory: /Users/davidcelis/Developer/firehydrant/laddertruck
2024-02-20 13:02:17.919 [info] (laddertruck) Ruby LSP> Skipping custom bundle setup since /Users/davidcelis/Developer/firehydrant/laddertruck/.ruby-lsp/Gemfile.lock already exists and is up to date

2024-02-20 13:02:17.937 [info] (laddertruck) Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2024-02-20 13:02:18.318 [info] (laddertruck) The Gemfile's dependencies are satisfied

2024-02-20 13:02:20.243 [info] (laddertruck) Starting Ruby LSP v0.14.0...

2024-02-20 13:02:20.632 [info] (laddertruck) Ruby LSP is ready

2024-02-20 13:02:28.226 [info] (laddertruck) Fetching Rails Documents…
```

Please let me know what kind of additional info I can provide and I'll be happy to do so as quickly as I can!

**Comment by KelseyDH** [comment]
@vinistock Ruby LSP does a network request to format code?

**Comment by vinistock** [comment]
@KelseyDH there are no network requests, that would be incredibly slow and brittle. We integrate directly with formatters and linters.

As described in [troubleshooting](https://shopify.github.io/ruby-lsp/troubleshooting.html#format-on-save-dialogue-wont-disappear), the format on save dialog not going away is a red herring. It doesn't mean that format on save specifically is hanging, it usually means that the server got into a bad state or crashed and the editor stopped receiving responses back.

Your issue is unlikely to be related to this one given that it was a crash all the way back to v0.14 and we're on v0.23.10. If you're on the latest version of the server (v0.23.10) and you're seeing the server get into a bad state, please open a new issue with details about your setup and if you notice specific steps that reproduce the issue.

**Comment by hron84** [comment]
The problem with this "red herring" window is VS Code does not save the content of the file until the formatter is not done if `editor.formatOnSave` setting is true. This can lead to data loss, so it should be solved anyway (even in a very bad state let the app save the file).

My VS code producing this exact issue with the hanging ruby-lsp process.

**Comment by kyletully** [comment]
Can confirm issue is still appearing on v0.9.7.
Noticed it a few days ago.

Currently Toggling "Editor Format On Save" On and Off to allow me to save and get past the hanging.

Will post the server state once it appears again.

VS Code 1.97.2 - Windows
Editing on remote Ubuntu host 24.04.1 LTS

Thanks for all your hard work! 👏

**Comment by caiomell0** [comment]
I'm currently experiencing the same problem. I use the cursor, and every time I try to save a file, the message Running 'Ruby LSP' Formatter (configure) appears.

It runs for a few seconds or even minutes, after which the LSP stops working in any other function.

I recently updated everything, and it didn't solve the problem.

**Comment by fffx** [comment]
I have to disable the formatter  `"rubyLsp.formatter": "none"` in setting.json
