### ISSUE TITLE
Weird Diagnostics for eruby

### ISSUE THREAD

**Issue by deniciocode** [Shopify/ruby-lsp#2439]
### Reproduction steps

1. Start LazyVim with mason installed and install ruby-lsp
2. Restart neovim
3. Open any `.html.erb` file
4. You see a lot of error diagnostics

**Code snippet or error message**
<img width="961" alt="image" src="https://github.com/user-attachments/assets/b952164c-9162-4174-8172-72984d06fad1">

**Comment by vinistock** [comment]
Thank you for the bug report! This was fixed by https://github.com/Shopify/ruby-lsp/pull/2432.

**Comment by deniciocode** [comment]
@vinistock after upgrading to `0.17.13`. We still have this issue shown
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/5a8d50bd-6810-46b4-be3f-9a3c127c7f58">

**Comment by st0012** [comment]
Have you tried the suggestions mentioned in https://github.com/Shopify/ruby-lsp/pull/2432#issuecomment-2288847806?
