### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by tsvallender** [Shopify/ruby-lsp#2446]
### Description

I am fairly regularly (probably about once a day at a full-time job) having ruby-lsp hit 100% CPU and stay there until I restart the process. I’m using the latest ruby-lsp with the Rails extension, in Neovim. I’ve seen this behaviour in multiple Ruby versions but am mostly in 3.3.4 currently.

I’m more than happy to do some work trying to figure out what’s causing this but am unsure where to start, any pointers appreciated.

**Comment by andyw8** [comment]
(and are you using ruby-lsp-rails, or only ruby-lsp?)

**Comment by tsvallender** [comment]
> @tsvallender if you are able to the LSP logs from just before it causes the CPU to peak, then that may help us to diagnose the problem.
> 
> Also, are you are on the latest release? (v0.17.13)

There hasn't been anything extra in the logs, and yes latest release. A colleague suggested stracing the process next time it happens so will see if that suggests anything. Always the way it doesn't happen when you're waiting for it...

**Comment by Earlopain** [comment]
I've had a hang somewhat recently (like maybe 1 month ago) as well but `strace` didn't show a thing. Process just kept doing things even after vscode was gone. Seems like this happens relativly often for you. How about you try adding the following to the ruby-lsp script:

```rb
Signal.trap("SIGUSR1") do
  output = +""
  Thread.list.each do |thr|
    output << ("-" * 40) << "\n"
    output << thr.inspect << "\n"
    output << thr.backtrace.join("\n") << "\n"
  end
  File.write("ruby-lsp-trace.log", output)
end if Signal.list.include?("USR1")
```

You can then do `kill -USR1 pid` where `pid` is somewhere in the output from `ps -aux | grep ruby-lsp`. I'm not sure how useful the output would actually be, its just something I used elsewhere. This should create a file with backtraces in the root of the project as long as you are not on windows.

This is all a bit awkward with the server auto-updating and all that, I wonder if this would be a generally useful addition for debugging things like this. There have been a few other issues with CPU pegging as their topic.

**Comment by Earlopain** [comment]
Certainly looks like something that could happen there, thought the only way I can think of is when edits are received out-of-order.

I coincidentally had another case today myself, though I failed to capture a stacktrace (oops). I'm going to add some logging to that method should we be running into the same thing.

**Comment by vinistock** [comment]
We received other reports of this and the thread is quite helpful. The referenced loop essentially turns a line + character position into the index that represents that position in the string we use to store the document's source code.

I'm not sure how we wouldn't be able to find the requested line and end up in an infinite loop though. We process text edits under a mutex lock, exactly to avoid having a feature request like signature help landing in between a thread switch (and thus trying to execute in a partially updated document).

If anyone can reproduce this reliably, we need to understand what piece of code triggers the problem.

Alternatively, we can also raise from that method if we reached the end of the document without finding anything and then include the state of the document and the position we were looking for. That might help diagnose it.

**Comment by adam12** [comment]
I've been chasing this one for a few months now as well. An alternative method I've used to capture the stack trace reliably is the `rbspy` tool.

I've observed two things when this has triggered:

1. Many times the `ruby-lsp` process has no ppid (parent). I am not sure this is connected tho.
2. Frequently, the task eventually completes and CPU usage returns to normal, so it's not likely to be an infinite loop.

I theorized that we were thrashing the GC somehow but wasn't able to get any deeper. It's near impossible to trigger by hand or via `ruby-lsp doctor`. It would be nice to be able to get Vernier enabled in a reproduction to see what the GC activity is like in order to rule it out.

**Comment by denvermullets** [comment]
if it's helpful, this triggers on my machine almost always now - to the point i've had to uninstall and i reinstall when i see an update is pushed - but if there are commands or anything that you would like me to run to help diagnose i am more than willing to help. 

i'm on an intel mac still, if that matters. i uninstalled it because i just got tired of it melting my battery down so quickly with bash processes that run 100%.

**Comment by denvermullets** [comment]
> [@denvermullets](https://github.com/denvermullets) meanwhile, a few questions to try to understand what's going on:
> 
> 1. What editor are you using?
> 2. What's the editor's encoding? UTF-8, UTF-16 or UTF-32?
> 3. Which line breaks do you use? `\n` or `\r\n`?
> 4. Do you notice this happening when doing something specific in your code? Like for example, does it always happen when you use multibyte characters like emojis or japanese characters?

sorry, missed this.

1. VS Code
2. UTF-8
3. none, the only line breaks in the small repos i see it happening only have the default `\n` in the rails setup files
4. i'm doing neither of those options

**Comment by Earlopain** [comment]
I've just had this happen to me again and I'm 99% sure I didn't interact with the editor when it happened. I was running some benchmark and the average went up since one core was saturated. The process had about 3 hours CPU time before it happened, so it ran for a while already. The window I had open at the time was a git diff, and that file is just boring utf8. Reloading vscode failed to kill the process, so I had to kill it manually.

I unfortunatly had no way to debug this since the server updated and I didn't put my things back in. strace only showed this:
`futex(0x563c18caca04, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY`, same as above.

**Comment by Aesthetikx** [comment]
This one happens to me essentially every day, neovim, M2 MacOS. I can help diagnose if someone points me in the right direction, no strace on MacOS so I can take a look with dtrace or equivalent perhaps.

**Comment by Aesthetikx** [comment]
> I think it would be handy if anyone sees it again to capture a recent stacktrace. Looking at the stacktrace above, it seems a bit out of date.

I can reliably reproduce this, my only issue is I only run MacOS and BSD at the moment, I'll see if I can get this going on a Linux box with strace. Maybe I'll see you in IRC later @adam12

**Comment by Aesthetikx** [comment]
I'll see if I can get this with a more up to date ruby-lsp, although I'm having trouble tricking neovim into using the latest version for some reason.

```
Time since start: 19s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
 71.23    71.23  == [c function] - (unknown)
 28.77   100.00  find_char_position - /Users/john/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.2/lib/ruby_lsp/document.rb:240
  0.00   100.00  text_document_completion - /Users/john/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.2/lib/ruby_lsp/server.rb:560
  0.00   100.00  process_message - /Users/john/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.2/lib/ruby_lsp/server.rb:89
  0.00   100.00  new [c function] - (unknown)
  0.00   100.00  initialize - /Users/john/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.2/lib/ruby_lsp/requests/completion.rb:105
  0.00   100.00  block in new_worker - /Users/john/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.17.2/lib/ruby_lsp/base_server.rb:130
  0.00   100.00  block in declare_abstract - /Users/john/.rbenv/versions/3.1.6/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11592/lib/types/private/abstract/declare.rb:42
```

**Comment by adam12** [comment]
Another idea might be running with `--debug` and see if you can get `rdbg` to break into the process once it triggers the 100% CPU scenario. Then perhaps do a bit of poking around (like `@source`, `@pos`, and `@encoding` might be of value).

I have been running with `--debug` for a few weeks now but either haven't seen the 100% CPU scenario with frequency and at least once, I could, but `rdbg` didn't see the socket.

Here's my Lua config.

```lua
local lspconfig = require('lspconfig')
lspconfig.ruby_lsp.setup({
  cmd = { 'ruby-lsp', '--debug', },
})
```

You'll want `rdbg -A` to break into the process.

**Comment by vinistock** [comment]
I'm still puzzled by this, but if people are willing to help diagnose this PR https://github.com/Shopify/ruby-lsp/pull/2664 has a bit more machinery to help.

Essentially, if the scanner fails to find the requested position, then we raise and print to the output tab the document state and the requested position that caused the failure. This should hopefully help us understand if the document state got corrupted.

To test on that branch, I believe it would be enough to put the `ruby-lsp` gem in the Gemfile and point to it.

**Comment by andyw8** [comment]
@Aesthetikx which vim distribution is that?

**Comment by Aesthetikx** [comment]
> [@Aesthetikx](https://github.com/Aesthetikx) which vim distribution is that?

@andyw8 

In this particular case LazyVim, which I do update regularly, I think however the issue is that it is not part of the LazyVim update screen, it is `:Mason` and then you can update the underlying LSP dependencies from there, which is why I was out of date. As for why it doesn't use a local version of ruby-lsp, who's to say?

**Comment by andyw8** [comment]
I'm not familiar with LazyVim or Mason, but there is an example config here that might help:

https://shopify.github.io/ruby-lsp/editors.html#lazyvim-lsp

**Comment by soda92** [comment]
I have get high CPU problem too, don't know if it's the same.

On windows 10 with neovim+ruby lsp

When I fire up two neovim instances editing Ruby code (so there are two ruby-lsp running), there starts to be ruby process consuming high CPU.

these processes exist even after exited neovim.

Also it's hard to kill them it seems they are spawn each other

**Comment by nanafox** [comment]
> I'm not familiar with LazyVim or Mason, but there is an example config here that might help:
> 
> https://shopify.github.io/ruby-lsp/editors.html#lazyvim-lsp
Thanks for this @andyw8 

I followed the recommendation and added the config. I'll keep monitoring the behavior now to see how this helps. But so far, it's not behaving as it used to (at least, for now). The only time I saw a spike was during the initial startup, after which CPU utilization went back to normal.

![Image](https://github.com/user-attachments/assets/bc824dd8-3a34-4efa-b85b-54cf73e0086b)

**Comment by andyw8** [comment]
@sathishmanohar I'm not familiar with Neoformat, but it doesn't seem like it supports LSP tooling: https://github.com/sbdchd/neoformat/issues/400

**Comment by jhawthorn** [comment]
I've been seeing this occasionally and managed to catch one in a `gdb`.

```
(gdb) bt 15
#0  rb_ident_hash (n=21) at hash.c:366
#1  0x00005a475d8cb9a0 in do_hash (key=0, tab=0x715f92fd28c0) at st.c:320
#2  rb_st_update (tab=tab@entry=0x715f92fd28c0, key=<optimized out>, key@entry=21, func=func@entry=0x5a475d78d6e0 <tbl_update_modify>, arg=arg@entry=140724160002272) at st.c:1447
#3  0x00005a475d78e84a in rb_hash_stlike_update (hash=124655301896360, key=21, func=0x5a475d78d6e0 <tbl_update_modify>, arg=140724160002272) at hash.c:1673
#4  rb_hash_stlike_update (hash=124655301896360, key=21, func=0x5a475d78d6e0 <tbl_update_modify>, arg=140724160002272) at hash.c:1661
#5  tbl_update (hash=hash@entry=124655301896360, key=21, func=func@entry=0x5a475d787590 <hash_aset_insert>, optional_arg=optional_arg@entry=9) at hash.c:1714
#6  0x00005a475d78e8f8 in rb_hash_aset (hash=124655301896360, key=<optimized out>, val=9) at hash.c:2946
#7  0x00005a475d900293 in exec_recursive (func=func@entry=0x5a475d7f04e0 <num_funcall_op_1>, obj=21, pairid=9, arg=arg@entry=140724160002720, outer=outer@entry=0, mid=<optimized out>) at thread.c:5238
#8  0x00005a475d910173 in rb_exec_recursive_paired (func=func@entry=0x5a475d7f04e0 <num_funcall_op_1>, obj=<optimized out>, paired_obj=<optimized out>, arg=arg@entry=140724160002720) at thread.c:5280
#9  0x00005a475d7f11e3 in num_funcall1 (x=<optimized out>, func=140, y=<optimized out>) at numeric.c:392
#10 num_equal (x=<optimized out>, y=<optimized out>) at numeric.c:1592
#11 fix_equal (x=<optimized out>, y=<optimized out>) at numeric.c:4617
#12 rb_int_equal (x=<optimized out>, y=<optimized out>) at numeric.c:4637
#13 0x00005a475d956682 in vm_call_cfunc_with_frame_ (ec=0x5a47808ae440, reg_cfp=0x715fac5fe948, calling=<optimized out>, argc=1, argv=0x715fac4ff620, stack_bottom=<optimized out>) at /home/jhawthorn/src/ruby-3.3.6/vm_insnhelper.c:3502
#14 0x00005a475d969600 in vm_sendish (method_explorer=<optimized out>, ec=<optimized out>, reg_cfp=<optimized out>, cd=<optimized out>, block_handler=<optimized out>) at /home/jhawthorn/src/ruby-3.3.6/vm_callinfo.h:403
(More stack frames follow...)
```

It's a bit odd to follow what it's running because this is an optimized build, but the `obj=21, pairid=9` gives us a hint. This is extra odd because this I think obj is an object (the tagged pointer representing the number `10`) and pairid=9 is the `object_id` (technically `rb_memory_id`) of `nil` then represented as a tagged pointer in C, so it's double tagged (nil -> 4 -> 9). So we're comparing `10` and `nil` 🤷‍♂

The function we're running is `==`.

I set a breakpoint in `rb_aref_internal` to try to validate the earlier theory that the `nil` comes from being out of bounds.

```
rb_ary_entry_internal (ary=<optimized out>, offset=7999447755) at internal/array.h:56
56          long len = RARRAY_LEN(ary);
(gdb) rp offset
FIXNUM: 3999723877
```

Seems like it!

**Comment by miguno** [comment]
Does https://github.com/Shopify/ruby-lsp/releases/tag/v0.23.1 include the potential fix?

**Comment by vinistock** [comment]
I just cut [v0.23.2](https://github.com/Shopify/ruby-lsp/releases/tag/v0.23.2) with what I hope is the fix. Please try it for some time and report back if you experience any issues.

**Comment by hotrungnhan** [comment]
even 0.23.13, this issue still exist, i'm using mac air m1, it reall really hot, my thigh is burning guy.

**Comment by hotrungnhan** [comment]
Although it doesn't happen as frequently as it used to, this problem still occurs frequently.  I've noticed that the LSP status looks like the picture below when the CPU reaches 100%.

<img width="588" alt="Image" src="https://github.com/user-attachments/assets/d6c32f9c-dab9-463b-87e2-ce137802be3b" />

**Comment by SlimGee** [comment]
It's June 2025 and this issue is still, ruby-lsp is using all my 12 cpus to 100% and it doesn't release them

**Comment by romanm-anyword** [comment]
@SlimGee there a fix should included in #3588 (v0.24.1). Can you confirm you're on latest version and CPU issue is still relevant?

**Comment by hotrungnhan** [comment]
@romanm-anyword 
I can clearly confirm that the latest `v0.9.27` ext with ruby-lsp `v0.24.1`  with vscode `1.100.3` still have that issue. It not disappear yet.

**Comment by SlimGee** [comment]
> [@SlimGee](https://github.com/SlimGee) there a fix should included in [#3588](https://github.com/Shopify/ruby-lsp/pull/3588) (v0.24.1). Can you confirm you're on latest version and CPU issue is still relevant?

@romanm-anyword I'm using `0.4.21` with neovim and same issue

**Comment by bdielman** [comment]
Still happening for me, although _only_ in VSCode. Neovim and Zed are fine as far as I can tell

**Comment by SlimGee** [comment]
I've switched to Solargraph for the time being

**Comment by HashNotAdam** [comment]
I have VSCode on two devices running different projects (all Rails). I've tried disabling all my other extensions and reinstalling the gem.

Interestingly, I just tried opening a Ruby gem and the new Ruby process seems to have settled down after indexing. I wonder if that means it's a Rails-only concern.

Please let me know if I can help with debugging, because I have to disable it on battery given how it smashes the CPU.

**Comment by andrcuns** [comment]
I can confirm that I have higher than usual cpu usage only for rails projects as well. Basic ruby non rails projects are working fine.

**Comment by romanm-anyword** [comment]
I wonder whether the issue is connected to the number of files in a project and any I/O operations.

**Comment by vinistock** [comment]
My mistake, there was a bug in the UTF-8 handling of position encodings. #3612 should fix it.

**Comment by hotrungnhan** [comment]
I'm afraid that this issue isn't fixed yet. Still have this using ver 0.24.2

**Comment by vinistock** [comment]
@hotrungnhan do you see issues similar to the ones reported in #3494? If not, then it might be a different problem with similar symptoms.

If it doesn't match #3494, can I ask that you please open a new issue? It might have a different root cause.

**Comment by romanm-anyword** [comment]
@vinistock 
How CPU utilization issue relates to #3494 ?

WDYT about comment https://github.com/Shopify/ruby-lsp/issues/2446#issuecomment-2975696108

**Comment by vinistock** [comment]
We were initially incorrectly translating editor positions to string indices for UTF-8, which is the encoding that gets negotiated when using NeoVim.

All of the backtraces included in this thread were pointing to our logic for this position translation ([example](https://github.com/Shopify/ruby-lsp/issues/2446#issuecomment-2293571823)). I'm fairly positive we had an infinite loop when translating UTF-8 locations and it also surfaced as corrupted document states when using multibyte characters (which is what is reported in #3494).

If there's another CPU issue, then the root cause is likely not the same as the one originally reported here (unless people are still seeing the problems in #3494).

To diagnose other performance issues, we need to understand which request is taking too long. Even more helpful if there's some profile data.

However, it could be something editor specific too. For example, we discovered that if we return too many semantic tokens to VS Code, the editor itself would lag when trying to apply them - regardless of how fast the server responds. We made changes to be more conservative in the number of tokens we return and that improved responsiveness in VS Code by many fold. Maybe in some response we're turning too much data and it's causing NeoVim to lag?

The number of files in the project will only impact indexing time and I wouldn't think IO is a problem here.

**Comment by hotrungnhan** [comment]
My project contains around 2,200 Ruby files.

I'm using the Ruby LSP, and the diagnostics keep showing the below logs.

I've noticed that there are usually two Ruby LSP processes running, and both consistently use over 90% CPU.

If they in "normal state", 1 processs is 0%, the other is roundly 50%.

That's all I have for now. If there's anything else I can do to help you diagnose the issue, just let me know—I'm happy to assist.

```
Worker alive: true
Incoming queue size: 0
Backtrace:
<internal:thread_sync>:18:in `pop'
/Users/kudousterain/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.24.2/lib/ruby_lsp/base_server.rb:146:in `block in new_worker'

=========== Documents (0) ===========
```

**Comment by vinistock** [comment]
I created #3663, so that we can gather context in a different issue - given that the root cause of this one is likely not the same. I added some instructions of how to diagnose. I appreciate the help in figuring this out, so that we can fix the experience for NeoVim users 🙏.
